version: '3.7'

services:
  interface:
    build: 
      context: ./interface/bank-system-interface
    container_name: interface
    networks:
      system-network:
        ipv4_address: 192.168.0.10
    environment:
      - IP_API_BROKER=192.168.0.10:8082
    ports:
      - "3000:3000"

  elevenbank:
    build:
      context: ./server
    container_name: elevenbank
    environment:
      - HOST_1=192.168.0.11
      - HOST_2=192.168.0.12
      - HOST_3=192.168.0.13
      - HOST_4=192.168.0.14
      - HOST_5=192.168.0.15
      - ID=1
    stdin_open: true
    tty: true
    ports:
      - "8081:8081"
    networks:
      system-network:
        ipv4_address: 192.168.0.11

  automobilibank:
    build:
      context: ./server
    container_name: automobilibank
    environment:
      - HOST_1=192.168.0.11
      - HOST_2=192.168.0.12
      - HOST_3=192.168.0.13
      - HOST_4=192.168.0.14
      - HOST_5=192.168.0.15
      - ID=2
    stdin_open: true
    tty: true
    ports:
      - "8082:8082"
    networks:
      system-network:
        ipv4_address: 192.168.0.12

  secretbank:
    build:
      context: ./server
    container_name: secretbank
    environment:
      - HOST_1=192.168.0.11
      - HOST_2=192.168.0.12
      - HOST_3=192.168.0.13
      - HOST_4=192.168.0.14
      - HOST_5=192.168.0.15
      - ID=3
    stdin_open: true
    tty: true
    ports:
      - "8083:8083"
    networks:
      system-network:
        ipv4_address: 192.168.0.13

  formulabank:
    build:
      context: ./server
    container_name: formulabank
    environment:
      - HOST_1=192.168.0.11
      - HOST_2=192.168.0.12
      - HOST_3=192.168.0.13
      - HOST_4=192.168.0.14
      - HOST_5=192.168.0.15
      - ID=4
    stdin_open: true
    tty: true
    ports:
      - "8084:8084"
    networks:
      system-network:
        ipv4_address: 192.168.0.14

  titaniumbank:
    build:
      context: ./server
    container_name: titaniumbank
    environment:
      - HOST_1=192.168.0.11
      - HOST_2=192.168.0.12
      - HOST_3=192.168.0.13
      - HOST_4=192.168.0.14
      - HOST_5=192.168.0.15
      - ID=5
    stdin_open: true
    tty: true
    ports:
      - "8085:8085"
    networks:
      system-network:
        ipv4_address: 192.168.0.15

networks:
  system-network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/24
